### ISSUE TITLE
Beta 5 fails when testing a windows store app

### ISSUE THREAD

**Issue by jwhite** [xunit/visualstudio.xunit#37]
This was tested with all libraries installed using nuget on a clean solution with all nuget references removed prior to testing.  This was on VS2015 preview.

------ Discover test started ------
[xUnit.net 00:00:00.0000006] Discovery started
[xUnit.net 00:00:00.1195398] Discovery starting: HydrometerTools.Test.dll
[xUnit.net 00:00:00.2497886] Discovery finished: HydrometerTools.Test.dll (2 tests)
[xUnit.net 00:00:00.2656595] Skipping: HydrometerTools.exe (no reference to xUnit.net)
[xUnit.net 00:00:00.2661948] Discovery complete
========== Discover test finished: 2 found (0:00:00.3740218) ==========
------ Run test started ------
Updating the layout...

Copying files: Total 1 mb to layout...

Registering the application to run from layout...

Deployment complete (303ms). Full package name: "058fd3e6-2367-4d2b-be6a-828ce1cb7916_1.0.0.0_neutral__nsmz8dbv8bkn8"

An exception occurred while invoking executor 'executor://xunit/VsTestRunner2': Could not load file or assembly 'xunit.runner.visualstudio.win8, Version=0.99.9.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
========== Run test finished: 0 run (0:00:00.9605035) ==========

Using beta5 caused this issue.

Downgrade xunit to beta4 using nuget reverts to a working behavior ----

******* BUT, only until reboot. ***********

At which point, if you reboot the tests are not discovered.

I presume this is because you need the beta4 libraries working with runner xunit.runner.visualstudio.win8 0.99.9-build1021 for the tests to be both detected and for them to be runnable and to have a successful configuration. 

It will run until reboot because the runner is not changed until the visual studio ide process restarts.

**Comment by jwhite** [comment]
I tried this on a completely clean VM image as well today with a clean install of VS 2015. 

Same error.  The nuget packages in the projects are as so :

<packages>
  <package id="xunit" version="2.0.0-beta5-build2785" targetFramework="win81" />
  <package id="xunit.abstractions" version="2.0.0-beta5-build2785" targetFramework="win81" />
  <package id="xunit.assert" version="2.0.0-beta5-build2785" targetFramework="win81" />
  <package id="xunit.core" version="2.0.0-beta5-build2785" targetFramework="win81" />
  <package id="xunit.runner.visualstudio.win8" version="0.99.9-build1021" targetFramework="win81" />
</packages>

Is this the correct runner version?

Same error.  Tests are discovered, but cannot be run.

Downgrading to build beta 4 everything works, until visual studio is restarted.

Then tests are not discovered.

Seems like a mismatch of version to me.....  are these the right packages?  They are what nuget hands out when you select the Beta 5 package.

**Comment by jwhite** [comment]
I pulled down the xunit source and notice that there are massive changes between beta4 and beta5.

Obviously, the xunit.runner.visualstudio.win8.dll can't be found.  Putting it manually inside the AppX folder (where it will be run) allows the runner to proceed.

Tests are then discovered and the runner starts.

It then throws this exception : 

[xUnit.net 00:00:00.0176053] Exception discovering tests from HydrometerTools.Test.dll: System.TypeLoadException: Method 'Find' in type 'Xunit.Sdk.XunitTestFrameworkDiscoverer' from assembly 'xunit.execution, Version=2.0.0.2785, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' does not have an implementation.
   at Xunit.Sdk.XunitTestFramework.CreateDiscoverer(IAssemblyInfo assemblyInfo)
   at Xunit.Sdk.TestFramework.GetDiscoverer(IAssemblyInfo assemblyInfo)
   at Xunit.Sdk.TestFrameworkProxy.GetDiscoverer(IAssemblyInfo assembly)
   at Xunit.Xunit2Discoverer..ctor(ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder)
   at Xunit.XunitFrontController.CreateInnerController()
   at Xunit.XunitFrontController.get_InnerController()
   at Xunit.XunitFrontController.get_TargetFramework()
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IEnumerable`1 sources, IMessageLogger logger, Func`3 visitorFactory, Action`3 visitComplete, Stopwatch stopwatch)

At this point I'm spinning my wheels trying to get my head around installing test extensions from nuget and how this whole build process for xUnit occurs.  It's rather complex.  A white paper on how it is put together would be very welcome -- at least one explaining the assembly relationships and how they work for each testing platform.

**Comment by bradwilson** [comment]
Can you upgrade to 2.0 RC1 and see if you're still having the problem?

**Comment by jwhite** [comment]
As I mentioned, any store tests (microsoft included) are completely broken or gone in CTP5.

I pulled down CTP4 and reinstalled clean with 2.0 RC1 (build 1030) and it still exhibits the same problem :

An exception occurred while invoking executor 'executor://xunit/VsTestRunner2': Could not load file or assembly 'xunit.runner.visualstudio.win8, Version=2.0.0.1030, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

I'm pretty sure that is because the dll isn't in the appx container when the tests run, but is the *.win8 assembly still required or is it now not needed?

**Comment by jwhite** [comment]
I think all you are missing to make 2015 CTP 4 work is the third dll in the nuget package needs to be added :

FILE : visualstudio.xunit\build\xunit.runner.visualstudio.win8.targets

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="AddXunitTestAdapterLibs" AfterTargets="_ComputeAppxPackagePayload" BeforeTargets="_GenerateAppxManifest">
    <ItemGroup>
      <xUnitVsLibs Include="$(MSBuildThisFileDirectory)xunit.runner.visualstudio.win8.dll">
        <TargetPath>xunit.runner.visualstudio.testadapter.dll</TargetPath>
      </xUnitVsLibs>
      <xUnitVsLibs Include="$(MSBuildThisFileDirectory)xunit.runner.utility.win8.dll">
        <TargetPath>xunit.runner.utility.win8.dll</TargetPath>
      </xUnitVsLibs>
	  <xUnitVsLibs Include="$(MSBuildThisFileDirectory)xunit.runner.visualstudio.win8.dll">
        <TargetPath>xunit.runner.visualstudio.win8.dll</TargetPath>
      </xUnitVsLibs>
      <xUnitVsLibsToRemove Include="@(AppxPackagePayload)" Condition="'%(TargetPath)' == 'xunit.runner.visualstudio.testadapter.dll'"/>
      <xUnitVsLibsToRemove Include="@(AppxPackagePayload)" Condition="'%(TargetPath)' == 'xunit.runner.utility.desktop.dll'"/>
      <AppxPackagePayload Remove="@(xUnitVsLibsToRemove)" />
      <AppxPackagePayload Include="@(xUnitVsLibs)" />
    </ItemGroup>
  </Target>
</Project>

I'd submit a proper fork with the change, but it is small and I'm not sure how difficult it is to test this without setting up a local nuget server......

I'm hoping the broken store tests in CTP 5 are just a temporary thing and not a sign of microsoft changing how things are done behind the scenes.

**Comment by bradwilson** [comment]
That's odd. Nothing should ever be linking against that thing with its old name. I'll take a look. Thanks for investigating.

**Comment by bradwilson** [comment]
This is fixed in RC2.

**Comment by xdaDaveShaw** [comment]
I'm trying this with RC2 and still seeing the same error:

> An exception occurred while invoking executor 'executor://xunit/VsTestRunner2': Could not load file or assembly 'xunit.runner.visualstudio.win8, Version=2.0.0.1043, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

I applied the suggestion from jwhite above and rebuild, it fixes things again.

This is a Win 8 Store app with xunit RC2 and runners.visualstudio.RC2 installed.
